name: Hello world

on:
  push:
    branches: ["master"]

jobs:
  hello:

    runs-on: ubuntu-latest

    steps:
      - name: Say Hello world
        run: echo "Hello world"

      - name: Check docker is installed
        run: docker --version

      - name: Build JAR with Maven
        run: mvn clean package
  
      - name: Login to Docker Hub works
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
