name: Java CI with Maven

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Verify Maven version in pom.xml
      run: |
        TAG_VERSION=${GITHUB_REF/refs\/tags\/v/}
        POM_VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)
        
        if [ "$TAG_VERSION" != "$POM_VERSION" ]; then
          echo "La versión del tag ($TAG_VERSION) no coincide con la versión en pom.xml ($POM_VERSION)"
          exit 1
        fi

    - name: Test with Maven
      run: mvn -B clean test

    - name: Package JAR
      run: mvn package

    - name: Set tag version as an environment variable
      run: echo "TAG_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/action-test-${TAG_VERSION}.jar
        tag_name: ${{ github.ref }}
        title: Release ${{ github.ref }}
        body: Auto-generate release notes
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}